# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

par_cpp <- function(rast_vals, ref_vals, samp_vals, intercept, nthreads = -1L) {
    .Call(`_gdmtools_par_cpp`, rast_vals, ref_vals, samp_vals, intercept, nthreads)
}

presist_cpp <- function(rast_vals, ref_vals, cond_vals, intercept, power = 0.25, nthreads = -1L) {
    .Call(`_gdmtools_presist_cpp`, rast_vals, ref_vals, cond_vals, intercept, power, nthreads)
}

